### ISSUE TITLE
Karto Memory usage behaviour

### ISSUE THREAD

**Issue by zoidzilla** [ros-perception/open_karto#28] opened 2022-12-06 12:33 UTC
Hello,

I am running Karto SLAM and I am monitoring the RES memory using the [cpu_monitor](https://github.com/alspitz/cpu_monitor) package. What I am getting is the following figure. Now, I understand that the memory usage builds up. What I don't understand is the memory behavior after 70MB (it continually allocates and frees a lot of memory blocks). I have seen and verify this behavior related to Karto in a number of publications that I found online (it is not related to the back-end optimization). However, I have not obtained any good explanation so far. Can you help?

Thank you!

![Karto_SLAM_Mem1](https://user-images.githubusercontent.com/2331748/205913565-2c888552-77d5-404c-ae69-82d143e492ab.jpg)

**Comment by mikeferguson** [comment] 2022-12-06 14:06
Duplicate of https://github.com/ros-perception/slam_karto/issues/36 - which is probably where the discussion belongs

**Closed as completed by mikeferguson** 2022-12-06 14:06 UTC
